version: '3'
services:
  model:
    build:
      context: .
      dockerfile: ./docker/model/Dockerfile
    ports:
      - 8081:8081
    networks:
      default:
        aliases:
          - mymodel

  controller:
    build:
      context: .
      dockerfile: ./docker/controller/Dockerfile
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - myconroller

  h2:
    image: oscarfonts/h2:latest
    hostname: h2
    ports:
      - 1521:1521
      - 81:81
      - 8082:8082

    networks:
      default:
         aliases:
            - database
